### ISSUE TITLE
AttributeError: 'module' object has no attribute '__version__'. in numpy.py

### ISSUE THREAD

**Issue by ylive001** [alanlhutchison/empirical-JTK_CYCLE-with-asymmetry#8]
Hi everyone,

I am a biologist and trying to run "empirical JTK", however, I ran into the following error message.

File "/home/gg/.local/lib/python2.7/site-packages/statsmodels/compat/numpy.py", line 46, in
NP_LT_114 = LooseVersion(np.version) < LooseVersion('1.14')
AttributeError: 'module' object has no attribute 'version'

Here are the package versions. I used "pip" to install all my packages
setuptools-44.1.1
numpy-1.16.6

Could anyone help me with this error? Any help is highly appreciated.

**Comment by weijuanliu** [comment]
Do you have solved this error? I have encountered this problem now and I don’t know how to solve it.Thank you
